spring:
  profiles:
    active: default, dubbo
  application:
    name: fast-llm-platform
server:
  port: 8081
logging:
  level:
    root: error
  pattern:
    console: '[%X{traceId:-}, %X{spanId:-}] %date %green(%level) %yellow([%thread]) %cyan(%logger{10}) [%file:%line] %msg%n'
  logback:
    rollingpolicy:
      max-file-size: 100MB
      total-size-cap: 1GB
      max-history: 1
      archive: true
      clean-history-on-start: true
      file-name-pattern: ./logs/fastx-llm-platform.%d{yyyy-MM-dd}.%i.gz.log

seata:
  enabled: true
  application-id: fastx-ai-llm-platform
  tx-service-group: default_tx_group
  service:
    default:
      grouplist:
        default: 127.0.0.1:8091
    grouplist:
      default: 127.0.0.1:8091
    # 事务分组与集群映射关系
    vgroup-mapping:
      default_tx_group: default
  registry:
    type: file
  config:
    type: file