server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  file:
    path: ${log.home:${user.home}/logs/seata}
console:
  user:
    username: seata
    password: seata
seata:
  security:
    secretKey: fast
    tokenValidityInMilliseconds: 30000000
  config:
    type: zk
    zk:
      server-addr: 172.17.0.3:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
      node-path: /seata/seata.properties
  registry:
    type: zk
    zk:
      cluster: default
      server-addr: 172.17.0.3:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
  server:
    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
    max-commit-retry-timeout: -1
    max-rollback-retry-timeout: -1
    rollback-failed-unlock-enable: false
    enable-check-auth: true
    enable-parallel-request-handle: true
    retry-dead-threshold: 130000
    xaer-nota-retry-timeout: 60000
    enableParallelRequestHandle: true
    recovery:
      committing-retry-period: 1000
      async-committing-retry-period: 1000
      rollbacking-retry-period: 1000
      timeout-retry-period: 1000
    undo:
      log-save-days: 7
      log-delete-period: 86400000
    session:
      branch-async-queue-size: 5000 #branch async remove queue size
      enable-branch-async-remove: false #enable to asynchronous remove branchSession
  store:
    mode: redis
    session:
      mode: redis
    lock:
      mode: redis
    redis:
      mode: single
      database: 0
      min-conn: 10
      max-conn: 100
      password:
      max-total: 100
      query-limit: 1000
      single:
        host: 172.17.0.4
        port: 6379
  transport:
    rpc-tc-request-timeout: 15000
    enable-tc-server-batch-send-response: false
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      boss-thread-size: 1