create table t_knowledge_base_file
(
    id                  bigint auto_increment
        primary key,
    knowledge_base_id   bigint                                                       not null,
    name                varchar(255)                                                 not null,
    extension           varchar(64)                                                  not null,
    download_url        text                                                         not null,
    vec_collection_name varchar(64)                                                  null,
    vec_collection_id   varchar(64)                                                  null,
    vec_partition_key   varchar(64)                                                  null,
    vec_partition_value varchar(64)                                                  null,
    status              enum ('active', 'process', 'wait') default 'wait'            not null,
    deleted             tinyint(1)                         default 0                 not null,
    create_time         timestamp                          default CURRENT_TIMESTAMP null,
    update_time         timestamp                          default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP
);

INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'logo.png', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/logo.png', null, null, null, null, 'wait', 1, '2024-12-14 08:42:52', '2024-12-14 10:14:41');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:14:36', '2024-12-15 02:18:19');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:16:57', '2024-12-15 02:18:19');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:16:59', '2024-12-15 02:18:19');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:17:01', '2024-12-15 02:18:19');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:17:07', '2024-12-14 10:15:02');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:18:06', '2024-12-14 10:15:02');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:18:15', '2024-12-14 10:15:02');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:18:18', '2024-12-14 10:15:02');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:18:20', '2024-12-14 10:15:02');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:18:22', '2024-12-14 10:15:02');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:19:13', '2024-12-14 10:14:59');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:19:58', '2024-12-14 10:14:59');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:20:00', '2024-12-14 10:14:59');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 09:20:02', '2024-12-14 10:14:59');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:00:34', '2024-12-14 10:14:58');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:01:23', '2024-12-14 10:14:58');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:05:04', '2024-12-14 10:15:01');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:05:07', '2024-12-14 10:15:01');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:05:11', '2024-12-14 10:15:01');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'LayoutsWorkspaceConfig.xml', 'xml', 'https://oss.fastx-ai.com/fastx-ai-llm/5/LayoutsWorkspaceConfig.xml', null, null, null, null, 'wait', 1, '2024-12-14 10:05:42', '2024-12-14 10:15:00');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (5, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/5/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:05:52', '2024-12-14 10:15:00');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (6, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/6/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:08:47', '2024-12-15 02:18:21');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (7, 'Adobe Premiere Pro Prefs', '-', 'https://oss.fastx-ai.com/fastx-ai-llm/7/Adobe Premiere Pro Prefs', null, null, null, null, 'wait', 1, '2024-12-14 10:09:42', '2024-12-15 02:18:16');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (8, '2412.09618v1.pdf', '09618v1.pdf', 'https://oss.fastx-ai.com/fastx-ai-llm/8/2412.09618v1.pdf', null, null, null, null, 'wait', 1, '2024-12-15 02:40:12', '2024-12-15 05:28:09');
INSERT INTO `fast-llm`.t_knowledge_base_file (knowledge_base_id, name, extension, download_url, vec_collection_name, vec_collection_id, vec_partition_key, vec_partition_value, status, deleted, create_time, update_time) VALUES (8, '2412.09618v1.pdf', '09618v1.pdf', 'https://oss.fastx-ai.com/fastx-ai-llm/8/2412.09618v1.pdf', null, null, null, null, 'wait', 0, '2024-12-15 05:28:19', '2024-12-15 05:28:19');
