
spring:
  profiles:
    active: default, dubbo, upload, redisson
  application:
    name: fast-llm-web
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
#  ai:
#    openai:
#      api-key: sk-02dOKWbd6R3oZ9CoBCbxELB348OnjJ6iFePyPqzQBm9lLv7x
#      base-url: https://open.xiaojingai.com/v1
#    stabilityai:
#      api-key: sk-QhpBqElSrrAnNRbA1aB9211bE4F64bC5A1E74b773017Ea81
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    max-swallow-size: 150MB

sa-token:
  token-name: satoken
  timeout: -1
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-read-header: true
  is-write-header: true